{% set name = "re2c" %}
{% set version = "3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/skvadrik/re2c/releases/download/{{ version }}/re2c-{{ version }}.tar.xz
  sha256: 0ac299ad359e3f512b06a99397d025cfff81d3be34464ded0656f8a96676c029

build:
  number: 0

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}           # [unix]
    - {{ compiler('cxx') }}         # [unix]
    - {{ compiler('m2w64_c') }}     # [win]
    - {{ compiler('m2w64_cxx') }}   # [win]
    - {{ posix }}make
    - posix                         # [win]

test:
  commands:
    - re2c --version

about:
  home: http://re2c.org
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'Lexer generator for C/C++ '
  doc_url: http://re2c.org/manual/manual.html
  dev_url: https://github.com/skvadrik/re2c

extra:
  recipe-maintainers:
    - isuruf
    - certik
