{% set name = "re2c" %}
{% set version = "4.0.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/skvadrik/re2c/releases/download/{{ version }}/re2c-{{ version }}.tar.xz
  sha256: 5e52ce0e26326115e41bc45d34dc2d5e10f2e44ed3a413fa2a826aa3500c8d56

build:
  number: 0

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}           # [unix]
    - {{ stdlib("c") }}             # [unix]
    - {{ compiler('cxx') }}         # [unix]
    - {{ compiler('m2w64_c') }}     # [win]
    - {{ stdlib("m2w64_c") }}       # [win]
    - {{ compiler('m2w64_cxx') }}   # [win]
    - {{ posix }}make
    - m2-base                         # [win]

test:
  commands:
    - re2c --version

about:
  home: http://re2c.org
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'Lexer generator for C/C++ '
  doc_url: http://re2c.org/manual/manual.html
  dev_url: https://github.com/skvadrik/re2c

extra:
  recipe-maintainers:
    - isuruf
    - certik
