{% set name = "re2c" %}
{% set version = "4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/skvadrik/re2c/releases/download/{{ version }}/re2c-{{ version }}.tar.xz
  sha256: 6b6b865924447ef992d5db4e52fb9307e5f65f26edd43efa91395da810f4280a

build:
  number: 1

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

test:
  commands:
    - re2c --version

about:
  home: http://re2c.org
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'Lexer generator for C/C++'
  doc_url: http://re2c.org/manual/manual.html
  dev_url: https://github.com/skvadrik/re2c

extra:
  recipe-maintainers:
    - isuruf
    - certik
