{% set name = "re2c" %}
{% set version = "4.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/skvadrik/re2c/releases/download/{{ version }}/re2c-{{ version }}.tar.xz
  sha256: de5431c1de9926ac6875c6d38eaedd14ba8f7fa54f3688bcca45b10006ab2ba6

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - python
    - diffutils  # [not win]
    - m2-diffutils  # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

test:
  commands:
    - re2c --version

about:
  home: http://re2c.org
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'Lexer generator for C/C++'
  doc_url: http://re2c.org/manual/manual.html
  dev_url: https://github.com/skvadrik/re2c

extra:
  recipe-maintainers:
    - isuruf
    - certik
