travis:
  secure:
    BINSTAR_TOKEN: s4bKDuEVDnBUnNUf6lKjRPOTp4HN1jjX2iiuQoEavKs+GiFTPwDRWoo4PjR9a2qPI0/P6UNWtL9ZAJqDf0ZlBVIUWSXDUTMVrwXCbvof5fdIg7TttHl7D4L5objsai0v/vhXFYKJrvA91G45+T2EutGp399SOmX8ElmQq4hsCty9Pcb+gFZC79IME5yuTcqot1EwI/qlxP+jrr2SocSORGJTlFv2jfpOvv75RZqUCUfjr8AExpCmIkovaNt7YQuPNypposvS1LyV6SSwdXljpbRd3HsjVK+jgIL4H7d7XxONK0hla8O4RtjagwciD3L+Vu607cXjbx5V3MOZdS9w5j0hpmA4bkVuNT+yPvJhA4SsBm4iMLFO/9XekQyg3wgVxhKwBj6Cq6uRbgkkJDJpILIGT2HYzrDaKhSURKX3WqRjm9y2q+xdxATlrM8Vb76BsZ9aaCcVswRpA0XhFYB86wp7vcV6G4fGMEUUk90Pm7Rz20weOJZ56E0RAOOgsjCyOoAXzCqQcvpM23KUuyhUftwapsHai/Wp8uZtjNORxu/69d89pPi4QpwPgShebuHfEvkF7U4WhW5bmp5cWPRnPTbDEIojB2KMtKIQdu77z8V99r3Flbdgut6Qqd0sOWlMWqZKqoP2twaKvz/7dmA3YW4/onWuTs5h/AlJWwFD/Yg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
